### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by easa** [store-php/StorePHP#3]
make an index.html page

**Comment by easa** [comment]
لطفا این در همون قالبی که صحبت کردیم انجام بشه

**Comment by fmamini** [comment]
قالبی که خواستید طراحی و اضافه شد

**Comment by easa** [comment]
خیلی خوب. 
برای این که دیزاینت خوب دیده بشه توشو با [محتوای بی معنی](http://loremipsum.ir/) با استفاده از این لینک پر کن

**Comment by easa** [comment]
فکر کن صفحه اصلی سایته. لطفا زیباش کن..
فایل css خودت رو هم بهش اضافه کن
