### ISSUE TITLE
Make PHP to handle DB

### ISSUE THREAD

**Issue by easa** [store-php/StorePHP#7]
### It's an improvement and may you want to add it on the next cycle! 

> So don't hurry

I'm wondering if you may handle the database things in your code so there be no other need to make a table or something by a user.

**Comment by waeliFatima** [comment]
I didn't write 'readme.md' for the users, i mean it for someone who want to try the code

**Comment by easa** [comment]
> I didn't write 'readme.md' for the users, i mean it for someone who want to try the code

I don't assume it as a good thing
